/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 carkey.gltf -t 
Author: neeb17 (https://sketchfab.com/neeb17)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/electronic-car-key-9e80efbaba8740288a77dcd165c3dedb
Title: Electronic Car Key
*/

import * as THREE from 'three'

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
  }
}


export function Carkey(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/carkey.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} position={[0, 0.532, 0]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} position={[0, 0.532, 0]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Material} position={[0, 0.532, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/carkey.gltf')
