/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 carPlate.gltf -t 
Author: Portfolio Rodrigues (https://sketchfab.com/portfoliorodrigues)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/placa-mercosul-brasil-brazilian-license-plate-0bc70edcc518472188e42e65224a505f
Title: Placa Mercosul Brasil | Brazilian License Plate
*/

import * as THREE from 'three'

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    plate: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
  }
}



export function CarPlate(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/carPlate.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={2.781}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.plate} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/carPlate.gltf')
