/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 itv.gltf -t 
Author: takeboncog (https://sketchfab.com/takeboncog)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-wrench-2734161713be4f97b9aa88c7c39e9e0a
Title: Low poly wrench
*/

import * as THREE from 'three'

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    DefaultMaterial: THREE.MeshStandardMaterial
  }
}



export function Itv(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/itv.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.009, 0]} rotation={[-0.368, 0.182, -0.201]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/itv.gltf')
