/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 mecanica.gltf -t 
Author: korsun (https://sketchfab.com/korsun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-lift-wheel-159e85a197d34d838f0e12ad002ed2e5
Title: Car lift + wheel
*/

import * as THREE from 'three'

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCylinder55_lambert1011__0: THREE.Mesh
    pCylinder24_lambert1024__0: THREE.Mesh
    pPlane1_lambert1023__0: THREE.Mesh
    pCylinder74_lambert1024__0: THREE.Mesh
    pCube39_lambert_10010_0: THREE.Mesh
    pCylinder77_lambert1024__0: THREE.Mesh
    polySurface127_lambert1013__0: THREE.Mesh
    polySurface102_lambert1011__0: THREE.Mesh
    polySurface120_lambert1013__0: THREE.Mesh
    pCylinder15_lambert1014__0: THREE.Mesh
    pCube5_lambert1014__0: THREE.Mesh
    pCylinder14_lambert1024__0: THREE.Mesh
    polySurface99_lambert1014__0: THREE.Mesh
    polySurface100_lambert1014__0: THREE.Mesh
    polySurface161_lambert1014__0: THREE.Mesh
    polySurface168_lambert1021__0: THREE.Mesh
    polySurface36_lambert1002__0: THREE.Mesh
    polySurface43_lambert1002__0: THREE.Mesh
    polySurface94_lambert1011__0: THREE.Mesh
    polySurface49_lambert1021__0: THREE.Mesh
    polySurface37_lambert1002__0: THREE.Mesh
    polySurface170_lambert1002__0: THREE.Mesh
    polySurface93_lambert1011__0: THREE.Mesh
    polySurface48_lambert1021__0: THREE.Mesh
    polySurface39_lambert1002__0: THREE.Mesh
    polySurface173_lambert1002__0: THREE.Mesh
    polySurface91_lambert1011__0: THREE.Mesh
    polySurface51_lambert1021__0: THREE.Mesh
    polySurface38_lambert1002__0: THREE.Mesh
    polySurface174_lambert1002__0: THREE.Mesh
    polySurface92_lambert1011__0: THREE.Mesh
    polySurface50_lambert1021__0: THREE.Mesh
    polySurface171_lambert1002__0: THREE.Mesh
    polySurface46_lambert1013__0: THREE.Mesh
    polySurface164_lambert1021__0: THREE.Mesh
    polySurface57_lambert1013__0: THREE.Mesh
    polySurface153_lambert1011__0: THREE.Mesh
    polySurface133_lambert1013__0: THREE.Mesh
    polySurface157_lambert1022__0: THREE.Mesh
    polySurface33_lambert1003_0: THREE.Mesh
    Cylinder004_lambert_1012__0: THREE.Mesh
    Cylinder004_lambert1_0: THREE.Mesh
    steering_wheel_lambert1003_0: THREE.Mesh
    polySurface4_lambert1024__0: THREE.Mesh
    polySurface61_lambert_1012__0: THREE.Mesh
    wheelLine012_lambert1021__0: THREE.Mesh
    wheelLine012_lambert1021__0_1: THREE.Mesh
    wheelCylinder004_lambert_1012__0: THREE.Mesh
    wheelCylinder004_lambert1_0: THREE.Mesh
    Bolts_lambert1013__0: THREE.Mesh
    car_partsdoors_lambert_10010_0: THREE.Mesh
  }
  materials: {
    lambert1011: THREE.MeshStandardMaterial
    lambert1024: THREE.MeshStandardMaterial
    lambert1023: THREE.MeshStandardMaterial
    lambert_10010: THREE.MeshStandardMaterial
    lambert1013: THREE.MeshStandardMaterial
    lambert1014: THREE.MeshStandardMaterial
    lambert1021: THREE.MeshStandardMaterial
    lambert1002: THREE.MeshStandardMaterial
    lambert1022: THREE.MeshStandardMaterial
    lambert1003: THREE.MeshStandardMaterial
    lambert_1012: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
  }
}


export function Mecanica(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/mecanica.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder55_lambert1011__0.geometry} material={materials.lambert1011} />
      <mesh geometry={nodes.pCylinder24_lambert1024__0.geometry} material={materials.lambert1024} />

      <mesh geometry={nodes.pCylinder74_lambert1024__0.geometry} material={materials.lambert1024} position={[14.71, 2.166, 34.263]} rotation={[0, -0.26, 0]} />
      <mesh geometry={nodes.pCube39_lambert_10010_0.geometry} material={materials.lambert_10010} />
      <mesh geometry={nodes.pCylinder77_lambert1024__0.geometry} material={materials.lambert1024} />
      <mesh geometry={nodes.polySurface127_lambert1013__0.geometry} material={materials.lambert1013} />
      <mesh geometry={nodes.polySurface102_lambert1011__0.geometry} material={materials.lambert1011} />
      <mesh geometry={nodes.polySurface120_lambert1013__0.geometry} material={materials.lambert1013} />
      <mesh geometry={nodes.pCylinder15_lambert1014__0.geometry} material={materials.lambert1014} rotation={[0, 0.038, 0]} />
      <mesh geometry={nodes.pCube5_lambert1014__0.geometry} material={materials.lambert1014} />
      <mesh geometry={nodes.pCylinder14_lambert1024__0.geometry} material={materials.lambert1024} rotation={[0, 0.038, 0]} />
      <mesh geometry={nodes.polySurface99_lambert1014__0.geometry} material={materials.lambert1014} position={[41.587, 294.067, 314.339]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[1, 3.276, 3.25]} />
      <mesh geometry={nodes.polySurface100_lambert1014__0.geometry} material={materials.lambert1014} position={[41.587, 294.067, 314.339]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[1, 3.276, 3.25]} />
      <mesh geometry={nodes.polySurface161_lambert1014__0.geometry} material={materials.lambert1014} />
      <mesh geometry={nodes.polySurface168_lambert1021__0.geometry} material={materials.lambert1021} />
      <mesh geometry={nodes.polySurface36_lambert1002__0.geometry} material={materials.lambert1002} />
      <mesh geometry={nodes.polySurface43_lambert1002__0.geometry} material={materials.lambert1002} position={[1.476, 0, -0.175]} />
      <mesh geometry={nodes.polySurface94_lambert1011__0.geometry} material={materials.lambert1011} position={[1.476, 0, -0.175]} />
      <mesh geometry={nodes.polySurface49_lambert1021__0.geometry} material={materials.lambert1021} position={[1.476, 0, 0]} />
      <mesh geometry={nodes.polySurface37_lambert1002__0.geometry} material={materials.lambert1002} position={[2.595, 0, -2.654]} rotation={[0, -0.572, 0]} />
      <mesh geometry={nodes.polySurface170_lambert1002__0.geometry} material={materials.lambert1002} position={[-5.81, 0, 2.554]} rotation={[0, -0.561, 0]} />
      <mesh geometry={nodes.polySurface93_lambert1011__0.geometry} material={materials.lambert1011} position={[-1.019, -0.099, -5.373]} rotation={[0, -0.572, 0]} />
      <mesh geometry={nodes.polySurface48_lambert1021__0.geometry} material={materials.lambert1021} position={[-1.086, -0.099, -5.35]} rotation={[0, -0.572, 0]} />
      <mesh geometry={nodes.polySurface39_lambert1002__0.geometry} material={materials.lambert1002} position={[2.082, 0, -24.522]} rotation={[0, -0.336, 0]} />
      <mesh geometry={nodes.polySurface173_lambert1002__0.geometry} material={materials.lambert1002} position={[80.686, 0, -9.64]} rotation={[-Math.PI, 0.326, -Math.PI]} />
      <mesh geometry={nodes.polySurface91_lambert1011__0.geometry} material={materials.lambert1011} position={[2.038, -0.117, -24.398]} rotation={[0, -0.336, 0]} />
      <mesh geometry={nodes.polySurface51_lambert1021__0.geometry} material={materials.lambert1021} position={[2.082, -0.117, -24.522]} rotation={[0, -0.336, 0]} />
      <mesh geometry={nodes.polySurface38_lambert1002__0.geometry} material={materials.lambert1002} position={[18.969, 0, 52.411]} rotation={[0, 0.78, 0]} />
      <mesh geometry={nodes.polySurface174_lambert1002__0.geometry} material={materials.lambert1002} position={[77.028, 0, -8.514]} rotation={[-Math.PI, -0.77, -Math.PI]} />
      <mesh geometry={nodes.polySurface92_lambert1011__0.geometry} material={materials.lambert1011} position={[22.584, 0, 48.809]} rotation={[0, 0.78, 0]} />
      <mesh geometry={nodes.polySurface50_lambert1021__0.geometry} material={materials.lambert1021} position={[22.584, 0, 48.809]} rotation={[0, 0.78, 0]} />
      <mesh geometry={nodes.polySurface171_lambert1002__0.geometry} material={materials.lambert1002} />
      <mesh geometry={nodes.polySurface46_lambert1013__0.geometry} material={materials.lambert1013} />
      <mesh geometry={nodes.polySurface164_lambert1021__0.geometry} material={materials.lambert1021} />
      <mesh geometry={nodes.polySurface57_lambert1013__0.geometry} material={materials.lambert1013} />
      <group position={[-21.806, -1023.388, -50.863]} rotation={[-3.133, -0.801, -1.555]} scale={0.007}>
        <mesh geometry={nodes.Cylinder004_lambert_1012__0.geometry} material={materials.lambert_1012} />
        <mesh geometry={nodes.Cylinder004_lambert1_0.geometry} material={materials.lambert1} />
      </group>
      <group position={[307.978, -505.886, -882.628]} rotation={[-3.088, -1.155, -2.583]} scale={0.007}>
        <mesh geometry={nodes.wheelLine012_lambert1021__0.geometry} material={materials.lambert1021} />
        <mesh geometry={nodes.wheelLine012_lambert1021__0_1.geometry} material={materials.lambert1021} />
      </group>
      <group position={[350.652, -504.416, -870.356]} rotation={[-3.14, -1.119, -2.635]} scale={0.007}>
        <mesh geometry={nodes.wheelCylinder004_lambert_1012__0.geometry} material={materials.lambert_1012} />
        <mesh geometry={nodes.wheelCylinder004_lambert1_0.geometry} material={materials.lambert1} />
      </group>
      <mesh geometry={nodes.polySurface133_lambert1013__0.geometry} material={materials.lambert1013} />
      <mesh geometry={nodes.polySurface153_lambert1011__0.geometry} material={materials.lambert1011} />
      <mesh geometry={nodes.polySurface157_lambert1022__0.geometry} material={materials.lambert1022} />
      <mesh geometry={nodes.polySurface33_lambert1003_0.geometry} material={materials.lambert1003} position={[29.918, 2.29, 28.319]} rotation={[0, -0.445, 0]} scale={0.806} />
      <mesh geometry={nodes.steering_wheel_lambert1003_0.geometry} material={materials.lambert1003} position={[100.98, 2.868, 52.187]} rotation={[-0.922, -0.237, -0.197]} scale={2.979} />
      <mesh geometry={nodes.polySurface4_lambert1024__0.geometry} material={materials.lambert1024} position={[39.968, 10.008, 12.592]} rotation={[0, -0.61, 0]} scale={0.602} />
      <mesh geometry={nodes.polySurface61_lambert_1012__0.geometry} material={materials.lambert_1012} position={[138.871, 2.485, 19.848]} rotation={[2.103, 1.179, 1.006]} scale={2.369} />
      <mesh geometry={nodes.Bolts_lambert1013__0.geometry} material={materials.lambert1013} position={[33.837, -8.172, -32.627]} rotation={[0.036, 1.117, -0.541]} scale={3.262} />
      <mesh geometry={nodes.car_partsdoors_lambert_10010_0.geometry} material={materials.lambert_10010} position={[111.794, -14.829, -27.277]} rotation={[0.007, 0, -0.225]} scale={3.982} />
    </group>
  )
}

useGLTF.preload('/mecanica.gltf')
