/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 toolbox.gltf -t 
Author: vicente betoret ferrero (https://sketchfab.com/deathcow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toolbox-f6506bf7f3b6439cb599f56ff931ff06
Title: Toolbox
*/

import * as THREE from 'three'

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    model_default007_0: THREE.Mesh
  }
  materials: {
    ['default.007']: THREE.MeshStandardMaterial
  }
}

export function Toolbox(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/toolbox.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model_default007_0.geometry} material={materials['default.007']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/toolbox.gltf')
