/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ventilador.gltf -t 
Author: Chouchou20 (https://sketchfab.com/Chouchou20)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ventilator-418fcd9d1996489faf6adbfc86cb167c
Title: ventilator
*/

import * as THREE from 'three'

import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    material: THREE.MeshPhysicalMaterial
    Blades: THREE.MeshStandardMaterial
    Plastic: THREE.MeshStandardMaterial
    Rubber: THREE.MeshStandardMaterial
  }
}



export function Ventilador(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ventilador.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.066}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Blades} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Rubber} />
      </group>
    </group>
  )
}

useGLTF.preload('/ventilador.gltf')
